title: W Parker MacKenzie
description: “...you know that human inventions march from the complex to the simple, and simplicity is always perfection.” - Alexandre Dumas, The Count of Monte Cristo
show_downloads: false
show_resume: true
contact_email: wparkermackenzie@outlook.com
contact_facebook: https://www.facebook.com/wpmackenzie
contact_github: https://github.com/wparkermackenzie
contact_linkedin: https://www.linkedin.com/in/wmackenzie/
contact_twitter: https://twitter.com/IoT_Engineer
contact_strava: https://www.strava.com/athletes/2691206
google_analytics:
theme: jekyll-theme-cayman
